import datetime
from typing import Any, Dict, List, Optional

def call_sales_api(products: Optional[List[str]] = None):
    data = get_sales_data()

    if products:
        return [item for item in data if item["product_id"] in products]
    
    return data


def get_sales_data() -> List[Dict[str, Any]]:
    return [
        {
            "date": datetime.date(2024, 1, 10),
            "product_id": "P001",
            "product_name": "Product 1",
            "quantity": 255,
            "revenue": 15547.35,
        },
        {
            "date": datetime.date(2024, 1, 10),
            "product_id": "P002",
            "product_name": "Product 2",
            "quantity": 65,
            "revenue": 2297.1,
        },
        {
            "date": datetime.date(2024, 1, 10),
            "product_id": "P003",
            "product_name": "Product 3",
            "quantity": 90,
            "revenue": 7301.7,
        },
        {
            "date": datetime.date(2024, 1, 10),
            "product_id": "P004",
            "product_name": "Product 4",
            "quantity": 171,
            "revenue": 8296.92,
        },
        {
            "date": datetime.date(2024, 1, 10),
            "product_id": "P005",
            "product_name": "Product 5",
            "quantity": 96,
            "revenue": 2587.2,
        },
        {
            "date": datetime.date(2024, 1, 11),
            "product_id": "P001",
            "product_name": "Product 1",
            "quantity": 235,
            "revenue": 14327.95,
        },
        {
            "date": datetime.date(2024, 1, 11),
            "product_id": "P002",
            "product_name": "Product 2",
            "quantity": 86,
            "revenue": 3039.24,
        },
        {
            "date": datetime.date(2024, 1, 11),
            "product_id": "P003",
            "product_name": "Product 3",
            "quantity": 79,
            "revenue": 6409.27,
        },
        {
            "date": datetime.date(2024, 1, 11),
            "product_id": "P004",
            "product_name": "Product 4",
            "quantity": 145,
            "revenue": 7035.4,
        },
        {
            "date": datetime.date(2024, 1, 11),
            "product_id": "P005",
            "product_name": "Product 5",
            "quantity": 114,
            "revenue": 3072.3,
        },
        {
            "date": datetime.date(2024, 1, 12),
            "product_id": "P001",
            "product_name": "Product 1",
            "quantity": 310,
            "revenue": 18900.7,
        },
        {
            "date": datetime.date(2024, 1, 12),
            "product_id": "P002",
            "product_name": "Product 2",
            "quantity": 80,
            "revenue": 2827.2,
        },
        {
            "date": datetime.date(2024, 1, 12),
            "product_id": "P003",
            "product_name": "Product 3",
            "quantity": 108,
            "revenue": 8762.04,
        },
        {
            "date": datetime.date(2024, 1, 12),
            "product_id": "P004",
            "product_name": "Product 4",
            "quantity": 143,
            "revenue": 6938.36,
        },
        {
            "date": datetime.date(2024, 1, 12),
            "product_id": "P005",
            "product_name": "Product 5",
            "quantity": 342,
            "revenue": 9216.9,
        },
        {
            "date": datetime.date(2024, 1, 13),
            "product_id": "P001",
            "product_name": "Product 1",
            "quantity": 302,
            "revenue": 18412.94,
        },
        {
            "date": datetime.date(2024, 1, 13),
            "product_id": "P002",
            "product_name": "Product 2",
            "quantity": 68,
            "revenue": 2403.12,
        },
        {
            "date": datetime.date(2024, 1, 13),
            "product_id": "P003",
            "product_name": "Product 3",
            "quantity": 96,
            "revenue": 7788.48,
        },
        {
            "date": datetime.date(2024, 1, 13),
            "product_id": "P004",
            "product_name": "Product 4",
            "quantity": 130,
            "revenue": 6307.6,
        },
        {
            "date": datetime.date(2024, 1, 13),
            "product_id": "P005",
            "product_name": "Product 5",
            "quantity": 103,
            "revenue": 2775.85,
        },
        {
            "date": datetime.date(2024, 1, 14),
            "product_id": "P001",
            "product_name": "Product 1",
            "quantity": 305,
            "revenue": 18595.85,
        },
        {
            "date": datetime.date(2024, 1, 14),
            "product_id": "P002",
            "product_name": "Product 2",
            "quantity": 84,
            "revenue": 2968.56,
        },
        {
            "date": datetime.date(2024, 1, 14),
            "product_id": "P003",
            "product_name": "Product 3",
            "quantity": 99,
            "revenue": 8031.87,
        },
        {
            "date": datetime.date(2024, 1, 14),
            "product_id": "P004",
            "product_name": "Product 4",
            "quantity": 167,
            "revenue": 8102.84,
        },
        {
            "date": datetime.date(2024, 1, 14),
            "product_id": "P005",
            "product_name": "Product 5",
            "quantity": 104,
            "revenue": 2802.8,
        },
        {
            "date": datetime.date(2024, 1, 15),
            "product_id": "P001",
            "product_name": "Product 1",
            "quantity": 301,
            "revenue": 18351.97,
        },
        {
            "date": datetime.date(2024, 1, 15),
            "product_id": "P002",
            "product_name": "Product 2",
            "quantity": 73,
            "revenue": 2579.82,
        },
        {
            "date": datetime.date(2024, 1, 15),
            "product_id": "P003",
            "product_name": "Product 3",
            "quantity": 89,
            "revenue": 7220.57,
        },
        {
            "date": datetime.date(2024, 1, 15),
            "product_id": "P004",
            "product_name": "Product 4",
            "quantity": 126,
            "revenue": 6113.52,
        },
        {
            "date": datetime.date(2024, 1, 15),
            "product_id": "P005",
            "product_name": "Product 5",
            "quantity": 100,
            "revenue": 2695.0,
        },
        {
            "date": datetime.date(2024, 1, 16),
            "product_id": "P001",
            "product_name": "Product 1",
            "quantity": 226,
            "revenue": 13779.22,
        },
        {
            "date": datetime.date(2024, 1, 16),
            "product_id": "P002",
            "product_name": "Product 2",
            "quantity": 80,
            "revenue": 2827.2,
        },
        {
            "date": datetime.date(2024, 1, 16),
            "product_id": "P003",
            "product_name": "Product 3",
            "quantity": 83,
            "revenue": 6733.79,
        },
        {
            "date": datetime.date(2024, 1, 16),
            "product_id": "P004",
            "product_name": "Product 4",
            "quantity": 175,
            "revenue": 8491.0,
        },
        {
            "date": datetime.date(2024, 1, 16),
            "product_id": "P005",
            "product_name": "Product 5",
            "quantity": 125,
            "revenue": 3368.75,
        },
    ]