
def get_dietary_restrictions() -> list[str]:
    return [
        "vegetarian",
        "vegan",
        "gluten-free",
        "dairy-free",
        "nut-free",
        "egg-free",
        "low-sodium",
        "keto",
        "paleo",
        "kosher",
    ]


def get_recipes() -> list[dict[str, any]]:
    return [
        {
            "name": "Classic Spaghetti Bolognese",
            "ingredients": [
                "1 lb ground beef",
                "1 onion, finely chopped",
                "2 garlic cloves, minced",
                "1 carrot, finely diced",
                "1 celery stalk, finely diced",
                "1 can (14 oz) crushed tomatoes",
                "2 tbsp tomato paste",
                "1 cup beef broth",
                "1 tsp dried oregano",
                "1 bay leaf",
                "1 lb spaghetti",
                "2 tbsp olive oil",
                "Salt and pepper to taste",
                "Grated Parmesan cheese for serving",
            ],
            "instructions": [
                "Heat olive oil in a large pot over medium heat.",
                "Add onion, garlic, carrot, and celery. Cook until softened, about 5 minutes.",
                "Add ground beef and cook until browned, breaking it up as it cooks.",
                "Stir in tomato paste and cook for 1 minute.",
                "Add crushed tomatoes, beef broth, oregano, bay leaf, salt, and pepper.",
                "Bring to a simmer, then reduce heat to low and cook for 1-2 hours.",
                "Cook spaghetti according to package instructions until al dente.",
                "Drain pasta and serve topped with the Bolognese sauce.",
                "Sprinkle with grated Parmesan cheese.",
            ],
        },
        {
            "name": "Vegetable Stir Fry",
            "ingredients": [
                "2 cups mixed vegetables (bell peppers, broccoli, carrots, snap peas)",
                "1 block firm tofu, cubed",
                "2 tbsp vegetable oil",
                "2 cloves garlic, minced",
                "1 tsp ginger, grated",
                "3 tbsp soy sauce",
                "1 tbsp rice vinegar",
                "1 tsp sesame oil",
                "1 tsp cornstarch",
                "2 green onions, sliced",
                "Sesame seeds for garnish",
                "Cooked rice for serving",
            ],
            "instructions": [
                "Press tofu to remove excess water, then cut into cubes.",
                "Mix soy sauce, rice vinegar, sesame oil, and cornstarch in a small bowl.",
                "Heat vegetable oil in a wok or large skillet over high heat.",
                "Add tofu and cook until golden, about 3-4 minutes. Remove and set aside.",
                "Add garlic and ginger to the wok and stir for 30 seconds.",
                "Add vegetables and stir-fry for 4-5 minutes until crisp-tender.",
                "Return tofu to the wok, add sauce mixture, and cook for 1-2 minutes until sauce thickens.",
                "Garnish with green onions and sesame seeds.",
                "Serve over rice.",
            ],
        },
        {
            "name": "Chocolate Chip Cookies",
            "ingredients": [
                "2 1/4 cups all-purpose flour",
                "1 tsp baking soda",
                "1 tsp salt",
                "1 cup (2 sticks) butter, softened",
                "3/4 cup granulated sugar",
                "3/4 cup packed brown sugar",
                "2 large eggs",
                "2 tsp vanilla extract",
                "2 cups semi-sweet chocolate chips",
                "1 cup chopped nuts (optional)",
            ],
            "instructions": [
                "Preheat oven to 375°F (190°C).",
                "Combine flour, baking soda, and salt in a small bowl.",
                "Beat butter, granulated sugar, and brown sugar in a large mixer bowl.",
                "Add eggs one at a time, beating well after each addition.",
                "Beat in vanilla extract.",
                "Gradually beat in flour mixture.",
                "Stir in chocolate chips and nuts if using.",
                "Drop by rounded tablespoon onto ungreased baking sheets.",
                "Bake for 9 to 11 minutes or until golden brown.",
                "Cool on baking sheets for 2 minutes; remove to wire racks to cool completely.",
            ],
        },
    ]